version: '3.7'

services:
  mongodb:
    image: mongo:latest  # Use the latest MongoDB image
    container_name: local-mongodb
    ports:
      - "27017:27017"  # Map MongoDB's default port to the host
    volumes:
      - mongodb_data:/data/db  # Persist data in a named volume
  task-management-service:  # Your Spring Boot service
    build: .  # Build the image from your Spring Boot project
    ports:
      - "8080:8080"  # Map your application's port
    depends_on:
      - mongodb  # Ensure MongoDB starts before your app
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/task-management
      # Connect to MongoDB using the container name 'mongodb'
volumes:
  mongodb_data:  # Define the named volume
