services:
  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-server
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links:
      - mongo-db
    networks:
      - task-mgmt-network

  mongo-db:
    image: mongo:7.0.14
    container_name: mongo-server
    environment:
      MONGO_INITDB_DATABASE: task-management
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      SPRING_DATA_MONGODB_URI: mongodb://mongo-server:27017/task-management
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - task-mgmt-network

  task-management-service:  # Your Spring Boot service
    build: .  # Build the image from your Spring Boot project
    ports:
      - "8080:8080"  # Map your application's port
    depends_on:
      - mongo-db  # Ensure MongoDB starts before your app
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo-server:27017/task-management
      # Connect to MongoDB using the container name 'mongodb'
    networks:
      - task-mgmt-network
networks:
  task-mgmt-network:
    driver: bridge
volumes:
  mongodb_data_container:
