/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.encora.taskmanagement.api;

import com.encora.taskmanagement.model.SignupRequest;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.Optional;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

@Generated(
    value = "org.openapitools.codegen.languages.SpringCodegen",
    comments = "Generator version: 7.4.0")
@Validated
@Controller
@Tag(name = "Authentication", description = "the Authentication API")
public interface AuthenticationApi {

  default Optional<NativeWebRequest> getRequest() {
    return Optional.empty();
  }

  /**
   * POST /signup : Register a new user
   *
   * @param signupRequest  (required)
   * @return User registered successfully (status code 201)
   *         or Bad Request - Invalid input data (status code 400)
   *         or Conflict - Email address already exists (status code 409)
   */
  @Operation(
      operationId = "signupPost",
      summary = "Register a new user",
      tags = {"Authentication"},
      responses = {
        @ApiResponse(responseCode = "201", description = "User registered successfully"),
        @ApiResponse(responseCode = "400", description = "Bad Request - Invalid input data"),
        @ApiResponse(responseCode = "409", description = "Conflict - Email address already exists")
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = "/signup",
      consumes = {"application/json"})
  default ResponseEntity<Void> signupPost(
      @Parameter(name = "SignupRequest", description = "", required = true) @Valid @RequestBody
          SignupRequest signupRequest) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }
}
